### ISSUE TITLE
Missing file "indirectpredicates/numerics.h"

### ISSUE THREAD

**Issue by dcoeurjo** [wangbolun300/fast-envelope#5]
When trying to replicate the paper results for https://replicability.graphics (https://github.com/GraphicsReplicability/replicability.graphics/pull/171), I got an issue with eigen (fixed in my PR) but one file is missing: `indirectpredicates/numerics.h` (used in `ip_filtered.h`).

**Comment by afabri** [comment]
I made the same observation, but it not really missing, but more a missing include path in a  CMakeScripts.txt.  As a workaround if you `#include <numerics.h>  it compiles (but then another target does not).

**Comment by dcoeurjo** [comment]
mmm... thx for the tip, Andreas.. I thought it was a specific `numerics.h`

**Comment by MarcoAttene** [comment]
That file is part of another repository (https://github.com/MarcoAttene/Indirect_Predicates). I have contacted the first author to see if it can be added as a submodule here

**Comment by dcoeurjo** [comment]
Oh, I see. thx @MarcoAttene

**Comment by teseoch** [comment]
Sorry for the inconvenience there was a problem with cmake which is now fixed.
To avoid this in the future we added CIs.

**Comment by dcoeurjo** [comment]
Thanks @teseoch. No more build issues
