### ISSUE TITLE
USE_ADJACENT_INFORMATION

### ISSUE THREAD

**Issue by afabri** [wangbolun300/fast-envelope#7]
Hello,  
I am wondering in which situation you would not use   `USE_ADJACENT_INFORMATION`   [here](https://github.com/wangbolun300/fast-envelope/blob/master/src/FastEnvelope.cpp#L3213)

**Comment by wangbolun300** [comment]
Sorry for the late response. 
The main considerarion was about performance. It is true that theoretically it will be enough if we only check the "real" intersection points created by two adjecent faces of one prism and the query triangle. But we found that if we do not consider about adjacency, the "pseudo intersections" created on the query triangle will help us find the prisms that cover this point earlier. Thus, setting `USE_ADJACENT_INFORMATION` as ON does not help improve the performance as far as we have seen in the experiments. That is why we considered about the adjacency in the beginning, but finally we decided to discard it.
