### ISSUE TITLE
bottom is not a nrighbor of top

### ISSUE THREAD

**Issue by afabri** [wangbolun300/fast-envelope#8]
I am wondering if for `i == 0`  and `j == 1`  where you return `true` [here](https://github.com/wangbolun300/fast-envelope/blob/master/src/FastEnvelope.cpp#L3609)  you should not test this and return `false`.    Or did I get your numbering scheme wrong.  This does not lead to a wrong envelope test, but leads to avoidable filter failures.

**Comment by wangbolun300** [comment]
Sorry for the late response. I think you are right, thanks for pointing this out. checking if (0,1) or (1,0) happens will avoid unnecessary check and improve the performance.  I will fix this problem.
